package com.softgen.gate.databaseHandler;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.softgen.gate.databaseHandler.Profile;
import com.softgen.gate.databaseHandler.Otp;

import com.softgen.gate.databaseHandler.ProfileDao;
import com.softgen.gate.databaseHandler.OtpDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig profileDaoConfig;
    private final DaoConfig otpDaoConfig;

    private final ProfileDao profileDao;
    private final OtpDao otpDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        profileDaoConfig = daoConfigMap.get(ProfileDao.class).clone();
        profileDaoConfig.initIdentityScope(type);

        otpDaoConfig = daoConfigMap.get(OtpDao.class).clone();
        otpDaoConfig.initIdentityScope(type);

        profileDao = new ProfileDao(profileDaoConfig, this);
        otpDao = new OtpDao(otpDaoConfig, this);

        registerDao(Profile.class, profileDao);
        registerDao(Otp.class, otpDao);
    }
    
    public void clear() {
        profileDaoConfig.getIdentityScope().clear();
        otpDaoConfig.getIdentityScope().clear();
    }

    public ProfileDao getProfileDao() {
        return profileDao;
    }

    public OtpDao getOtpDao() {
        return otpDao;
    }

}
