package com.softgen.gate.databaseHandler;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "OTP".
 */
public class Otp {

    private Long id;
    private int otpNumber;
    /** Not-null value. */
    private String mobileNo;
    /** Not-null value. */
    private String email;
    /** Not-null value. */
    private java.util.Date createdAt;
    /** Not-null value. */
    private java.util.Date updatedAt;
    private long ProfileId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Otp() {
    }

    public Otp(Long id) {
        this.id = id;
    }

    public Otp(Long id, int otpNumber, String mobileNo, String email, java.util.Date createdAt, java.util.Date updatedAt, long ProfileId) {
        this.id = id;
        this.otpNumber = otpNumber;
        this.mobileNo = mobileNo;
        this.email = email;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.ProfileId = ProfileId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getOtpNumber() {
        return otpNumber;
    }

    public void setOtpNumber(int otpNumber) {
        this.otpNumber = otpNumber;
    }

    /** Not-null value. */
    public String getMobileNo() {
        return mobileNo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public java.util.Date getCreatedAt() {
        return createdAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreatedAt(java.util.Date createdAt) {
        this.createdAt = createdAt;
    }

    /** Not-null value. */
    public java.util.Date getUpdatedAt() {
        return updatedAt;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdatedAt(java.util.Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public long getProfileId() {
        return ProfileId;
    }

    public void setProfileId(long ProfileId) {
        this.ProfileId = ProfileId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
